  Introduction : 'Attacks with StyleGAN2.'
  optim : 'GAN_based'    #optim method, ['GAN_based', 'GAN_free']
  cost_fn : 'sim_cmpr0'   #the type of loss function 
  set_seed : 0         # random seed. Following GIAS, we set 0 as seed for StyleGAN2(FFHQ).
  indices : 'def'      #decide which part of gradients to be involved in the final gradients match loss.
  weights : 'equal'    #weight of every graident scalar's matching loss
  init : 'randn'     #how we initial the original latent code.
  model : 'ResNet18'   #FL model
  restarts : 4

  num_images : 1   # the number of images to reconstruct at a batch
  num_exp : 10     # the number of experiments
  target_id : 0
  lr : 0.03
  total_variation : 0.0001     #the coefficient of total variation
  bn_stat : 0       #choose if we use bn statistic to regularizer
  image_norm : 0.000001    #the coefficient of norm regularizer
  group_lazy : 0    #choose if we use group lazy regularization
  
  max_iterations : 1000   #Maximum number of iterations for latent reconstruction.

  #For GIAS
  gias_iterations : 8000  #Maximum number of gias iterations for reconstruction.
  gias_lr : 0.001
  
  # For input data

  generative_model : 'stylegan2_io'
  gen_dataset : 'FFHQ64'
  dataset : 'FFHQ64'
  data_path : './dataset/FFHQ-128'    # specify your dataset path

  #For output data
  exp_name : 'ex1_stylegan2_ffhq'   #Same latent space search
  output_dir : 'results/'


  #params for algorithm choice
  gifd : true
  gias : false
  ggl : false

  #For GIFD with stylegan2
  steps : [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]      #8000 in total
  lr_io: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  start_layer: 0
  end_layer: 8      #fixed

  # For l-1 projection
  project : true
  do_project_gen_out: true
  do_project_noises: true
  do_project_latent: true
  max_radius_gen_out: [1000, 2000, 3000, 4000, 5000, 6000, 8000, 8000]
  max_radius_noises: [1000, 2000, 3000, 4000, 5000, 6000, 8000, 8000]
  max_radius_latent: [1000, 2000, 3000, 4000, 5000, 6000, 8000, 8000]

  # The pre-trained StyleGAN checkpoint
  ckpt: './inversefed/genmodels/stylegan2_io/stylegan2-ffhq-config-f.pt'

  #LR pace for training
  lr_same_pace: false 

  #Defense parameter
  defense_method : None
  defense_setting : 
      - noise : None
      - clipping : None
      - compression : None
      - representation : None


  #For CMA-ES
  KLD : 0  
  cma_budget : 800
  num_sample : 50  #sample times


  #cmd instruction
  # python rec_mult.py --config configs_stylegan2.yml
  