name: GILO
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=9.2.0=py38hace64e9_0
  - pip=22.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.12.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.0=py38_cu102
  - torchvision=0.13.0=py38_cu102
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.9=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - antlr4-python3-runtime==4.8
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - bayesian-optimization==1.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - boto3==1.24.36
    - botocore==1.27.36
    - cachetools==5.2.0
    - cma==3.2.2
    - cycler==0.11.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.9.1
    - fastjsonschema==2.16.1
    - fonttools==4.34.4
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - gpytorch==1.8.0
    - grpcio==1.47.0
    - hydra==2.5
    - hydra-core==1.0.6
    - imageio==2.22.2
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.1.0
    - jsonschema==4.8.0
    - jupyter==1.0.0
    - jupyter-client==7.3.4
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - lpips==0.1.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.7
    - nevergrad==0.5.0
    - ninja==1.11.1
    - notebook==6.4.12
    - oauthlib==3.2.0
    - omegaconf==2.0.6
    - opencv-python==4.4.0.46
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-pretrained-biggan==0.1.1
    - pytz==2022.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - runipy==0.1.5
    - s3transfer==0.6.0
    - scikit-image==0.17.2
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - send2trash==1.8.0
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tinycss2==1.1.1
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.1
    - widgetsnbextension==3.6.1
    - zipp==3.8.1
prefix: /home/itml_fh/anaconda3/envs/GGL
